version: "3.8"
services:
  mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql/db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    networks:
      - bun

  jetstream:
    image: "ghcr.io/juni-b-queer/jetstream-new:personal-branch"
    container_name: jetstream
    restart: unless-stopped
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

  remindbot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
      - jetstream
    volumes:
      - ./sessionData:/sessionData
    networks:
      - bun

networks:
  bun:
    driver: bridge

#volumes:
#  volmysql:
#    driver: local