export const REPLIES = [
    'nobody asked',
    'no one cares',
    'who cares',
    'you\'re wrong',
    'delete ur account',
    'go touch grass',
    'no one knows what you\'re talking about',
    'you need to stop',
    'we\'re not interested',
    'spare us the details',
    'that\'s irrelevant',
    'why bother mentioning it?',
    'save your breath',
    'nobody needs your input',
    'don\'t flatter yourself',
    'keep your opinions to yourself',
    'nobody\'s soliciting your views',
    'we didn\'t request your insight',
    'stop wasting your breath',
    'no one gives a damn',
    'just keep it to yourself',
    'we could do without your input',
    'your opinion is unwelcome',
    'you\'re not adding any value',
    'we don\'t need your two cents',
    'spare us the nonsense',
    'why even mention it?',
    'we don\'t care about your view'
]